# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Convert_1bit_Tiffs_to8bit_Png.py
# Created on: 2015-04-28 16:09:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import os
import arcpy

inputFolder = arcpy.GetParameterAsText(0)
outputFolder = arcpy.GetParameterAsText(1)
arcpy.env.workspace = inputFolder
# Local variables:
rasters = arcpy.ListRasters(None, "TIF")

for tiff in rasters:

    tifImage = os.path.join(inputFolder,tiff)
    pngImage = os.path.join(outputFolder,tiff.replace("tif","png"))

    tempEnvironment0 = arcpy.env.newPrecision
    arcpy.env.newPrecision = "SINGLE"
    tempEnvironment1 = arcpy.env.autoCommit
    arcpy.env.autoCommit = "1000"
    tempEnvironment2 = arcpy.env.XYResolution
    arcpy.env.XYResolution = ""
    tempEnvironment3 = arcpy.env.XYDomain
    arcpy.env.XYDomain = ""
    tempEnvironment4 = arcpy.env.scratchWorkspace
    arcpy.env.scratchWorkspace = "C:\\Users\\Administrator\\Documents\\ArcGIS\\Default.gdb"
    tempEnvironment5 = arcpy.env.cartographicPartitions
    arcpy.env.cartographicPartitions = ""
    tempEnvironment6 = arcpy.env.terrainMemoryUsage
    arcpy.env.terrainMemoryUsage = "false"
    tempEnvironment7 = arcpy.env.MTolerance
    arcpy.env.MTolerance = ""
    tempEnvironment8 = arcpy.env.compression
    arcpy.env.compression = "LZ77"
    tempEnvironment9 = arcpy.env.coincidentPoints
    arcpy.env.coincidentPoints = "MEAN"
    tempEnvironment10 = arcpy.env.randomGenerator
    arcpy.env.randomGenerator = "0 ACM599"
    tempEnvironment11 = arcpy.env.outputCoordinateSystem
    arcpy.env.outputCoordinateSystem = ""
    tempEnvironment12 = arcpy.env.rasterStatistics
    arcpy.env.rasterStatistics = "STATISTICS 1 1"
    tempEnvironment13 = arcpy.env.ZDomain
    arcpy.env.ZDomain = ""
    tempEnvironment14 = arcpy.env.transferDomains
    arcpy.env.transferDomains = "false"
    tempEnvironment15 = arcpy.env.resamplingMethod
    arcpy.env.resamplingMethod = "NEAREST"
    tempEnvironment16 = arcpy.env.snapRaster
    arcpy.env.snapRaster = ""
    tempEnvironment17 = arcpy.env.projectCompare
    arcpy.env.projectCompare = "NONE"
    tempEnvironment18 = arcpy.env.cartographicCoordinateSystem
    arcpy.env.cartographicCoordinateSystem = "PROJCS['Monte_Mario_Italy_1',GEOGCS['GCS_Monte_Mario',DATUM['D_Monte_Mario',SPHEROID['International_1924',6378388.0,297.0]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['false_easting',1500000.0],PARAMETER['false_northing',0.0],PARAMETER['central_meridian',9.0],PARAMETER['scale_factor',0.9996],PARAMETER['latitude_of_origin',0.0],UNIT['Meter',1.0]]"
    tempEnvironment19 = arcpy.env.configKeyword
    arcpy.env.configKeyword = ""
    tempEnvironment20 = arcpy.env.outputZFlag
    arcpy.env.outputZFlag = "Same As Input"
    tempEnvironment21 = arcpy.env.qualifiedFieldNames
    arcpy.env.qualifiedFieldNames = "true"
    tempEnvironment22 = arcpy.env.tileSize
    arcpy.env.tileSize = "128 128"
    tempEnvironment23 = arcpy.env.parallelProcessingFactor
    arcpy.env.parallelProcessingFactor = ""
    tempEnvironment24 = arcpy.env.pyramid
    arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
    tempEnvironment25 = arcpy.env.referenceScale
    arcpy.env.referenceScale = ""
    tempEnvironment26 = arcpy.env.extent
    arcpy.env.extent = "DEFAULT"
    tempEnvironment27 = arcpy.env.XYTolerance
    arcpy.env.XYTolerance = ""
    tempEnvironment28 = arcpy.env.tinSaveVersion
    arcpy.env.tinSaveVersion = "CURRENT"
    tempEnvironment29 = arcpy.env.nodata
    arcpy.env.nodata = "NONE"
    tempEnvironment30 = arcpy.env.MDomain
    arcpy.env.MDomain = ""
    tempEnvironment31 = arcpy.env.spatialGrid1
    arcpy.env.spatialGrid1 = "0"
    tempEnvironment32 = arcpy.env.cellSize
    arcpy.env.cellSize = "MAXOF"
    tempEnvironment33 = arcpy.env.outputZValue
    arcpy.env.outputZValue = ""
    tempEnvironment34 = arcpy.env.outputMFlag
    arcpy.env.outputMFlag = "Same As Input"
    tempEnvironment35 = arcpy.env.geographicTransformations
    arcpy.env.geographicTransformations = "NAD_1927_To_NAD_1983_NADCON;NAD_1927_To_NAD_1983_NADCON"
    tempEnvironment36 = arcpy.env.spatialGrid2
    arcpy.env.spatialGrid2 = "0"
    tempEnvironment37 = arcpy.env.ZResolution
    arcpy.env.ZResolution = ""
    tempEnvironment38 = arcpy.env.mask
    arcpy.env.mask = ""
    tempEnvironment39 = arcpy.env.spatialGrid3
    arcpy.env.spatialGrid3 = "0"
    tempEnvironment40 = arcpy.env.maintainSpatialIndex
    arcpy.env.maintainSpatialIndex = "false"
    tempEnvironment41 = arcpy.env.workspace
    arcpy.env.workspace = "C:\\Users\\Administrator\\Documents\\ArcGIS\\Default.gdb"
    tempEnvironment42 = arcpy.env.MResolution
    arcpy.env.MResolution = ""
    tempEnvironment43 = arcpy.env.derivedPrecision
    arcpy.env.derivedPrecision = "HIGHEST"
    tempEnvironment44 = arcpy.env.ZTolerance
    arcpy.env.ZTolerance = ""

    arcpy.CopyRaster_management(tifImage, pngImage, "", "", "", "OneBitTo8Bit", "NONE", "", "NONE", "NONE")

    arcpy.AddMessage("{0} was converted to .Png in folder {1}".format(tiff, str(outputFolder)))

    arcpy.env.newPrecision = tempEnvironment0
    arcpy.env.autoCommit = tempEnvironment1
    arcpy.env.XYResolution = tempEnvironment2
    arcpy.env.XYDomain = tempEnvironment3
    arcpy.env.scratchWorkspace = tempEnvironment4
    arcpy.env.cartographicPartitions = tempEnvironment5
    arcpy.env.terrainMemoryUsage = tempEnvironment6
    arcpy.env.MTolerance = tempEnvironment7
    arcpy.env.compression = tempEnvironment8
    arcpy.env.coincidentPoints = tempEnvironment9
    arcpy.env.randomGenerator = tempEnvironment10
    arcpy.env.outputCoordinateSystem = tempEnvironment11
    arcpy.env.rasterStatistics = tempEnvironment12
    arcpy.env.ZDomain = tempEnvironment13
    arcpy.env.transferDomains = tempEnvironment14
    arcpy.env.resamplingMethod = tempEnvironment15
    arcpy.env.snapRaster = tempEnvironment16
    arcpy.env.projectCompare = tempEnvironment17
    arcpy.env.cartographicCoordinateSystem = tempEnvironment18
    arcpy.env.configKeyword = tempEnvironment19
    arcpy.env.outputZFlag = tempEnvironment20
    arcpy.env.qualifiedFieldNames = tempEnvironment21
    arcpy.env.tileSize = tempEnvironment22
    arcpy.env.parallelProcessingFactor = tempEnvironment23
    arcpy.env.pyramid = tempEnvironment24
    arcpy.env.referenceScale = tempEnvironment25
    arcpy.env.extent = tempEnvironment26
    arcpy.env.XYTolerance = tempEnvironment27
    arcpy.env.tinSaveVersion = tempEnvironment28
    arcpy.env.nodata = tempEnvironment29
    arcpy.env.MDomain = tempEnvironment30
    arcpy.env.spatialGrid1 = tempEnvironment31
    arcpy.env.cellSize = tempEnvironment32
    arcpy.env.outputZValue = tempEnvironment33
    arcpy.env.outputMFlag = tempEnvironment34
    arcpy.env.geographicTransformations = tempEnvironment35
    arcpy.env.spatialGrid2 = tempEnvironment36
    arcpy.env.ZResolution = tempEnvironment37
    arcpy.env.mask = tempEnvironment38
    arcpy.env.spatialGrid3 = tempEnvironment39
    arcpy.env.maintainSpatialIndex = tempEnvironment40
    arcpy.env.workspace = tempEnvironment41
    arcpy.env.MResolution = tempEnvironment42
    arcpy.env.derivedPrecision = tempEnvironment43
    arcpy.env.ZTolerance = tempEnvironment44

