# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# copy_to_oracle_ase_ESRI_SERVIZIOSIT.py
# Created on: 2015-04-22 09:17:16.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import os
import arcpy


# Local variables:
inputFolder = arcpy.GetParameterAsText(0)

# Set the workspace environment to local file geodatabase
arcpy.env.workspace = inputFolder

shpFiles = arcpy.ListFeatureClasses()

destinationFeatureDataset = arcpy.GetParameter(1)
destFD = str(destinationFeatureDataset)

fcSuffix = arcpy.GetParameterAsText(2)
#                  Database Connections\geodb_exat_as_ESRI_SERVIZIOSIT.sde\ESRI_SERVIZIOSIT.DBT_2012_RDN_TM32
FEATURE_DATASET = "Database Connections\\geodb_exat_as_ESRI_SERVIZIOSIT.sde\\ESRI_SERVIZIOSIT.DBT_2012_RDN_TM32\\"
if not os.path.isdir(os.path.join(arcpy.env.workspace, "already_loaded")):
    os.makedirs(os.path.join(arcpy.env.workspace, "already_loaded"))

for shp in shpFiles:
    shpNoExt = shp.replace(".shp","")

    # Process: Copy Features
    arcpy.CopyFeatures_management(shp, destFD+"\\ESRI_SERVIZIOSIT."+shpNoExt+fcSuffix, "", "0", "0", "0")
    msg = "{0} copied to Oracle".format(shp)
    print msg
    arcpy.AddMessage(msg)
    shpAssemblyList = [assPart for assPart in os.listdir(arcpy.env.workspace) if shpNoExt in assPart]
    for part in shpAssemblyList:
        os.rename(os.path.join(arcpy.env.workspace, part),os.path.join(arcpy.env.workspace, "already_loaded", part))
