# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Defin_Projection_GB_for_folder.py
# Created on: 2015-04-04 12:22:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import os
import arcpy


# Dynamic variables:
rasterFolder = arcpy.GetParameterAsText(0)

# Set the workspace environment to local file geodatabase
arcpy.env.workspace = rasterFolder

rasters = arcpy.ListRasters()

spatialReference = arcpy.GetParameter(1)
projection = spatialReference.exportToString()

# Process: Define Projection
if rasters != None:
    tot = len(rasters)
    arcpy.AddMessage("{0} rasters found in input folder".format(str(tot)))
    i = 0.0
    for raster in rasters:
        i = i+1.0
        arcpy.DefineProjection_management(raster, projection)
        msg = "{0:.2%} : Projection for raster {1} was set.".format((i/tot),str(raster))
        arcpy.AddMessage(msg)
else:

    arcpy.AddWarning("No rasters found in input folder {0}".format(str(rasterFolder)))