# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Define_NoData_255_onRasterFolder_8bit.py
# Created on: 2015-05-12 11:21:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

# Dynamic variables:
rasterFolder = arcpy.GetParameterAsText(0)

# Set the workspace environment to local file geodatabase
arcpy.env.workspace = rasterFolder

rasters = arcpy.ListRasters()

# Process: Define Projection
if rasters != None:
    tot = len(rasters)
    arcpy.AddMessage("{0} rasters found in input folder".format(str(tot)))
    i = 0.0
    for raster in rasters:
	i = i+1.0
	# Process: Set Raster Properties
	arcpy.SetRasterProperties_management(raster, "GENERIC", "", "", "1 255")
	msg = "{0:.2%} : No-Data for raster {1} was set to 255.".format((i/tot),str(raster))
        arcpy.AddMessage(msg)
