# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Defin_Projection_GB_for_folder.py
# Created on: 2015-04-04 12:22:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import os
import arcpy


# Dynamic variables:
rasterFolder = arcpy.GetParameterAsText(0)

# Set the workspace environment to local file geodatabase
arcpy.env.workspace = rasterFolder

rasters = arcpy.ListRasters()

spatialReference = arcpy.GetParameter(1)
projection = spatialReference.exportToString()

# Process: Define Projection
if rasters != None:
    for raster in rasters:
        arcpy.DefineProjection_management(raster, projection)

