# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Project2_Raster_Folder_from_ETRS89_to_WebMercator.py
# Created on: 2015-04-08 13:41:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import os
import arcpy

# Dynamic variables:
rasterFolderInput = arcpy.GetParameterAsText(0)
rasterFolderOutput = arcpy.GetParameterAsText(1)

# Set the workspace environment to local file geodatabase
arcpy.env.workspace = rasterFolderInput

rasters = arcpy.ListRasters()

# Process: Define Projection
if rasters != None:
    for raster in rasters:

        inRaster = os.path.join(rasterFolderInput, raster)
        outRaster = os.path.join(rasterFolderOutput, raster)

        # Process: Project Raster
        arcpy.AddMessage("About to process Raster {} ...".format(str(raster)))
        arcpy.ProjectRaster_management(inRaster, outRaster, "PROJCS['WGS_1984_Web_Mercator_Auxiliary_Sphere',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator_Auxiliary_Sphere'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],PARAMETER['Auxiliary_Sphere_Type',0.0],UNIT['Meter',1.0]]", "NEAREST", "0,635 0,635", "ETRS_1989_To_WGS_1984", "", "PROJCS['ETRS_1989_UTM_Zone_32N',GEOGCS['GCS_ETRS_1989',DATUM['D_ETRS_1989',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['false_easting',500000.0],PARAMETER['false_northing',0.0],PARAMETER['central_meridian',9.0],PARAMETER['scale_factor',0.9996],PARAMETER['latitude_of_origin',0.0],UNIT['Meter',1.0]]")
        arcpy.AddMessage("\nRaster {} was processed.".format(str(raster)))
