# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Rename_append_suffix.py
# Created on: 2015-04-22 14:18:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import os
import arcpy

# Local variables:
inputWorkspaceOrFeatureDataset = arcpy.GetParameterAsText(0)
suffix = arcpy.GetParameterAsText(1)

# Set the workspace environment to local file geodatabase
arcpy.env.workspace = inputWorkspaceOrFeatureDataset

shpFiles = arcpy.ListFeatureClasses()

# Local variables:
# "Database Connections\\geodb_exat_as_ESRI_SERVIZIOSIT.sde\\ESRI_SERVIZIOSIT.DBT_2012_GB\\ESRI_SERVIZIOSIT.A000201"
# outputName = "Database Connections\\geodb_exat_as_ESRI_SERVIZIOSIT.sde\\ESRI_SERVIZIOSIT.DBT_2012_GB\\ESRI_SERVIZIOSIT.A000201_Rename"

for shp in shpFiles:
    inputName = os.path.join(arcpy.env.workspace, shp)
    outputName = os.path.join(arcpy.env.workspace, shp+suffix)

    #shpNoExt = shp.replace(".shp","")

    # Process: Rename
    if suffix not in shp:
        arcpy.Rename_management(inputName, outputName, "FeatureClass")
        msg = "{0} was renamed to {1}".format(shp, shp+suffix)
        print msg
        arcpy.AddMessage(msg)
        '''
        shpAssemblyList = [assPart for assPart in os.listdir(arcpy.env.workspace) if shpNoExt in assPart]
        for part in shpAssemblyList:
            os.rename(os.path.join(arcpy.env.workspace, part),os.path.join(arcpy.env.workspace, "already_loaded", part))
        '''